export const GET_ACTIVE_PLAN_REQUEST = "GET_ACTIVE_PLAN_REQUEST";
export const GET_ACTIVE_PLAN_SUCCESS = "GET_ACTIVE_PLAN_SUCCESS";
export const GET_ACTIVE_PLAN_ERROR = "GET_ACTIVE_PLAN_ERROR";

export const UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_REQUEST = "UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_REQUEST";
export const UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_SUCCESS = "UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_SUCCESS";
export const UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_ERROR = "UPDATE_ONE_TIME_PAYMENT_HIT_COUNT_ERROR";
